apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-gateway
  template:
    metadata:
      labels:
        app: web-gateway
    spec:
      containers:
      - name: web-gateway
        image: maciejgum/web-gateway:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: web-gateway-env
          - secretRef:
              name: web-gateway-sec

        resources:
          limits:
            {}

        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          
